### ISSUE TITLE
Segfault in memcpy / do_ssl3_write

### ISSUE THREAD

**Issue by jlu5** [jlu5/PyLink#585]
Running Python 3.5.3 and 2.0 Git:

```
#0  __memmove_avx_unaligned_erms () at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:242
#1  0x00007f57f1cebfb5 in memcpy (__len=<optimized out>, __src=<optimized out>, __dest=0x7f57b805b510) at /usr/include/x86_64-linux-gnu/bits/string3.h:53
#2  do_ssl3_write (s=s@entry=0x7f57b8003780, type=type@entry=23, buf=buf@entry=0x7f57ee4afb13 "w\352U", pipelens=pipelens@entry=0x7f57aa7fb030, numpipes=1, 
    create_empty_fragment=create_empty_fragment@entry=0) at ../ssl/record/rec_layer_s3.c:798
#3  0x00007f57f1cec53b in ssl3_write_bytes (s=0x7f57b8003780, type=23, buf_=0x7f57ee4a3b00, len=<optimized out>) at ../ssl/record/rec_layer_s3.c:599
#4  0x00007f57f1cfcba9 in SSL_write (s=<optimized out>, buf=<optimized out>, num=<optimized out>) at ../ssl/ssl_lib.c:1605
#5  0x00007f57f08d0fca in _ssl__SSLSocket_write_impl.isra.21 (self=0x7f57ee4a9540) at ./Modules/_ssl.c:1914
#6  _ssl__SSLSocket_write.lto_priv.35 () at ./Modules/clinic/_ssl.c.h:214
#7  0x000055ea76c68cac in call_function (oparg=<optimized out>, pp_stack=0x7f57aa7fb300) at ../Python/ceval.c:4705
#8  PyEval_EvalFrameEx () at ../Python/ceval.c:3251
#9  0x000055ea76c6893f in fast_function (nk=<optimized out>, na=<optimized out>, n=<optimized out>, pp_stack=0x7f57aa7fb430, func=<optimized out>) at ../Python/ceval.c:4818
#10 call_function (oparg=<optimized out>, pp_stack=0x7f57aa7fb430) at ../Python/ceval.c:4745
#11 PyEval_EvalFrameEx () at ../Python/ceval.c:3251
#12 0x000055ea76c6d286 in _PyEval_EvalCodeWithName () at ../Python/ceval.c:4033
#13 0x000055ea76c690a9 in fast_function (nk=<optimized out>, na=<optimized out>, n=<optimized out>, pp_stack=0x7f57aa7fb640, func=<optimized out>) at ../Python/ceval.c:4828
#14 call_function (oparg=<optimized out>, pp_stack=0x7f57aa7fb640) at ../Python/ceval.c:4745
#15 PyEval_EvalFrameEx () at ../Python/ceval.c:3251
#16 0x000055ea76c6893f in fast_function (nk=<optimized out>, na=<optimized out>, n=<optimized out>, pp_stack=0x7f57aa7fb770, func=<optimized out>) at ../Python/ceval.c:4818
#17 call_function (oparg=<optimized out>, pp_stack=0x7f57aa7fb770) at ../Python/ceval.c:4745
#18 PyEval_EvalFrameEx () at ../Python/ceval.c:3251
#19 0x000055ea76c6e0df in _PyEval_EvalCodeWithName (qualname=0x0, name=<optimized out>, closure=0x0, kwdefs=0x0, defcount=0, defs=0x0, kwcount=0, kws=<optimized out>, 
    argcount=<optimized out>, args=<optimized out>, locals=<optimized out>, globals=<optimized out>, _co=<optimized out>) at ../Python/ceval.c:4033
#20 PyEval_EvalCodeEx () at ../Python/ceval.c:4054
#21 0x000055ea76caa7bf in function_call.lto_priv () at ../Objects/funcobject.c:627
#22 0x000055ea76cf1647 in PyObject_Call () at ../Objects/abstract.c:2166
#23 0x000055ea76c66180 in ext_do_call (nk=<optimized out>, na=<optimized out>, flags=<optimized out>, pp_stack=0x7f57aa7fba28, func=<function at remote 0x7f57f023bae8>)
    at ../Python/ceval.c:5049
#24 PyEval_EvalFrameEx () at ../Python/ceval.c:3290
#25 0x000055ea76c6893f in fast_function (nk=<optimized out>, na=<optimized out>, n=<optimized out>, pp_stack=0x7f57aa7fbb50, func=<optimized out>) at ../Python/ceval.c:4818
#26 call_function (oparg=<optimized out>, pp_stack=0x7f57aa7fbb50) at ../Python/ceval.c:4745
#27 PyEval_EvalFrameEx () at ../Python/ceval.c:3251
#28 0x000055ea76c6893f in fast_function (nk=<optimized out>, na=<optimized out>, n=<optimized out>, pp_stack=0x7f57aa7fbc80, func=<optimized out>) at ../Python/ceval.c:4818
#29 call_function (oparg=<optimized out>, pp_stack=0x7f57aa7fbc80) at ../Python/ceval.c:4745
#30 PyEval_EvalFrameEx () at ../Python/ceval.c:3251
#31 0x000055ea76c6e0df in _PyEval_EvalCodeWithName (qualname=0x0, name=<optimized out>, closure=0x0, kwdefs=0x0, defcount=0, defs=0x0, kwcount=0, kws=<optimized out>, 
    argcount=<optimized out>, args=<optimized out>, locals=<optimized out>, globals=<optimized out>, _co=<optimized out>) at ../Python/ceval.c:4033
#32 PyEval_EvalCodeEx () at ../Python/ceval.c:4054
#33 0x000055ea76caa5d3 in function_call.lto_priv () at ../Objects/funcobject.c:627
#34 0x000055ea76cf1647 in PyObject_Call () at ../Objects/abstract.c:2166
#35 0x000055ea76c1194e in method_call.lto_priv () at ../Objects/classobject.c:330
#36 0x000055ea76cf1647 in PyObject_Call () at ../Objects/abstract.c:2166
#37 0x000055ea76ca4e30 in PyEval_CallObjectWithKeywords () at ../Python/ceval.c:4595
#38 0x000055ea76d39962 in t_bootstrap () at ../Modules/_threadmodule.c:998
#39 0x00007f57f3d65494 in start_thread (arg=0x7f57aa7fc700) at pthread_create.c:333
#40 0x00007f57f2f58aff in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97
```

bt full of first few frames:

```
#0  __memmove_avx_unaligned_erms () at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:242
No locals.
#1  0x00007f57f1cebfb5 in memcpy (__len=<optimized out>, __src=<optimized out>, __dest=0x7f57b805b510) at /usr/include/x86_64-linux-gnu/bits/string3.h:53
No locals.
#2  do_ssl3_write (s=s@entry=0x7f57b8003780, type=type@entry=23, buf=buf@entry=0x7f57ee4afb13 "w\352U", pipelens=pipelens@entry=0x7f57aa7fb030, numpipes=1, 
    create_empty_fragment=create_empty_fragment@entry=0) at ../ssl/record/rec_layer_s3.c:798
        outbuf = {0x7f57b805b508 "\347\260D\340?\306\061\271w\352U", 
          0x55ea76cf15b6 <_Py_CheckFunctionResult+38> "H\205\333t%H\205\300\017\205;\217\357\377H\211\330H\213L$\030dH3\f%(", 0x0, 
          0x86e95fe05475c800 <error: Cannot access memory at address 0x86e95fe05475c800>, 0x7f57f41760a0 <incomplete sequence \327>, 
          0x86e95fe05475c800 <error: Cannot access memory at address 0x86e95fe05475c800>, 0x55ea7717ecf0 <_PyThreadState_Current> "\300\315\271w\352U", 
          0x55ea76c4f329 <PyErr_Occurred+9> "H\205\300\017\204I\274\364\377H\213@PH\203\304\b\303\017\037D", 
          0x55ea76ca8690 <PyCFunction_Call> "AUATUSH\211\375H\203\354\030H\213G\020\213X\020L\213h\b\366\303 uI\203\343\217L\213g\030\203\373\003tHH\205\322\017\205\244", 
          0x55ea76cf15b6 <_Py_CheckFunctionResult+38> "H\205\333t%H\205\300\017\205;\217\357\377H\211\330H\213L$\030dH3\f%(", 0x1 <error: Cannot access memory at address 0x1>, 
          0x7f57f0bc4728 "\001", 0x7f57ec06abd0 "", 0x86e95fe05475c800 <error: Cannot access memory at address 0x86e95fe05475c800>, 0x1 <error: Cannot access memory at address 0x1>, 
          0x7f57ec0b86d8 "", 0x7f57aa7fa540 "q\023\327v\352U", 0x55ea76cf278f <PyObject_CallMethodObjArgs+415> "H\215\005Z\305H", 
          0x3000000018 <error: Cannot access memory at address 0x3000000018>, 0x7f57aa7fa630 "", 0x7f57aa7fa540 "q\023\327v\352U", 
          0x86e95fe05475c800 <error: Cannot access memory at address 0x86e95fe05475c800>, 0x55ea76d71371 "U:write", 0x7f57f2a5eae0 "\006", 0x7f57ee47ddc8 "", 0x0, 
          0x1 <error: Cannot access memory at address 0x1>, 0x0, 0x7f57b8010090 "\360\016\001\270W\177", 0x55ea76c5428e <PyArg_ParseTupleAndKeywords+190> "H\213t$\030dH34%(", 
          0x7f57f0bc4728 "\001", 0x55ea77168ee0 <_PyManagedBuffer_Type> "\003"}
        plen = {0x7f57b805b506 "@\030\347\260D\340?\306\061\271w\352U", 0x55ea76c457bb <_PyObject_GC_New+59> "H\205\300H\211\303\017\204\211\001", 0x7f57f40e4f28 "", 
          0x55ea77168d40 <PyMemoryView_Type> "&", 0x3 <error: Cannot access memory at address 0x3>, 0x55ea76c44a53 <_PyObject_GC_NewVar+67> "H\205\300H\211\303\017\204\231", 
          0x7f57f40e4f28 "", 0x0, 0x1 <error: Cannot access memory at address 0x1>, 0x55ea76cc5890 <PyMemoryView_FromBuffer+272> "H\205\300H\211\305\017\204e\005", 
          0x55ea7717ecf0 <_PyThreadState_Current> "\300\315\271w\352U", 0x55ea76d71372 ":write", 0x7f57f0bc4728 "\001", 
          0x55ea76cf4005 <PyNumber_AsSsize_t+37> "H\203\370\377H\211\305t\"H\203+\001\017\204\211", 0x7f57ec06abd0 "", 0x0, 0x55ea77197580 <small_ints.lto_priv+1984> "\020", 
          0x55ea76c3f2a9 <PyThread_release_lock+9> "\205\300\017\205M\362\364\377H\203\304\b\303f.\017\037\204", 0x7f57aa7fc698 "", 
          0x55ea76c0a6f7 <buffered_flush+247> "H\211\350H\213t$hdH34%(", 0x0, 0x0, 
          0x55ea77a5a2e0 "2018-03-12 03:46:03,740 [DEBUG] (buddy) -> :90A ENDBURST\nost: IRCd=inspircd, host=cloaked-fc3.4rq.224.24.IP\n\ndy).\net='324AAAEPM'\n1520851563 +iw + :ZNC - https://znc.in\ntats*', 'MrC*', 'Lily', 'Ethan',"..., 0x0, 0x39 <error: Cannot access memory at address 0x39>, 0x1 <error: Cannot access memory at address 0x1>, 
          0x100000001 <error: Cannot access memory at address 0x100000001>, 0x7f57f411aa78 "\037", 0x7f57f0bb0448 "\001", 
          0x74232d2738d6cdb4 <error: Cannot access memory at address 0x74232d2738d6cdb4>, 0x7f57f0b74088 "\001", 0x55ea77a52648 "\005"}
        wr = {{rec_version = 0, type = 23, length = 16384, orig_len = 0, off = 0, data = 0x7f57b805b510 "w\352U", input = 0x7f57ee4afb13 "w\352U", comp = 0x0, read = 0, epoch = 0, 
            seq_num = "\000\000\000\000\000\000\000"}, {rec_version = 0, type = 0, length = 0, orig_len = 0, off = 0, data = 0x0, input = 0x0, comp = 0x0, read = 0, epoch = 0, 
            seq_num = "\000\000\000\000\000\000\000"} <repeats 31 times>}
        i = <optimized out>
        mac_size = 0
        clear = <optimized out>
        prefix_len = <optimized out>
        eivlen = 8
        align = <optimized out>
        wb = <optimized out>
        sess = <optimized out>
        totlen = 16384
        j = 0
```

**Comment by jlu5** [comment]
Can't seem to reproduce with 2.0.0 final, maybe this was fixed in an earlier connection handling rework: f274088ea0d14ffab04b73007bbd0c32bf80cfdb 75869897630aadcdfdc3478f41a90453b1ae28ed 80cbd7a2575b93126573cd53d305406826a52c7b 138a52611ed63e9fcba170994897c479eaeced40
