### ISSUE TITLE
Segfault in _int_malloc / new_keys_object

### ISSUE THREAD

**Issue by jlu5** [jlu5/PyLink#587]
```
#0  _int_malloc (av=av@entry=0x7fe288000020, bytes=bytes@entry=224) at malloc.c:3554
#1  0x00007fe2c9928f34 in __GI___libc_malloc (bytes=224) at malloc.c:2928
#2  0x000056495bcb325b in new_keys_object (size=8) at ../Objects/dictobject.c:324
#3  PyDict_New () at ../Objects/dictobject.c:408
#4  0x000056495bc5bbad in _PyEval_EvalCodeWithName (qualname=0x0, name=<optimized out>, closure=0x0, kwdefs=0x0, defcount=2, defs=0x7fe2c80547a0, kwcount=0, kws=<optimized out>, 
    argcount=10, args=0x7fe2c5f1fe60, locals=<optimized out>, globals=<optimized out>, _co=<optimized out>) at ../Python/ceval.c:3838
#5  PyEval_EvalCodeEx () at ../Python/ceval.c:4054
#6  0x000056495bc97648 in function_call.lto_priv () at ../Objects/funcobject.c:627
#7  0x000056495bcde647 in PyObject_Call () at ../Objects/abstract.c:2166
#8  0x000056495bbfe94e in method_call.lto_priv () at ../Objects/classobject.c:330
#9  0x000056495bcde647 in PyObject_Call () at ../Objects/abstract.c:2166
#10 0x000056495bc9eaa9 in slot_tp_init () at ../Objects/typeobject.c:6287
#11 0x000056495bca65c4 in type_call.lto_priv () at ../Objects/typeobject.c:905
#12 0x000056495bcde647 in PyObject_Call () at ../Objects/abstract.c:2166
#13 0x000056495bc55ee1 in do_call (nk=<optimized out>, na=9, pp_stack=0x7fe290ff7e40, func=<optimized out>) at ../Python/ceval.c:4951
#14 call_function (oparg=<optimized out>, pp_stack=0x7fe290ff7e40) at ../Python/ceval.c:4747
#15 PyEval_EvalFrameEx () at ../Python/ceval.c:3251
#16 0x000056495bc5a286 in _PyEval_EvalCodeWithName () at ../Python/ceval.c:4033
#17 0x000056495bc560a9 in fast_function (nk=<optimized out>, na=<optimized out>, n=<optimized out>, pp_stack=0x7fe290ff8050, func=<optimized out>) at ../Python/ceval.c:4828
#18 call_function (oparg=<optimized out>, pp_stack=0x7fe290ff8050) at ../Python/ceval.c:4745
#19 PyEval_EvalFrameEx () at ../Python/ceval.c:3251
#20 0x000056495bc5b0df in _PyEval_EvalCodeWithName (qualname=0x0, name=<optimized out>, closure=0x0, kwdefs=0x0, defcount=3, defs=0x7fe2c8049f00, kwcount=0, kws=<optimized out>, 
    argcount=<optimized out>, args=<optimized out>, locals=<optimized out>, globals=<optimized out>, _co=<optimized out>) at ../Python/ceval.c:4033
#21 PyEval_EvalCodeEx () at ../Python/ceval.c:4054
#22 0x000056495bc977bf in function_call.lto_priv () at ../Objects/funcobject.c:627
#23 0x000056495bcde647 in PyObject_Call () at ../Objects/abstract.c:2166
#24 0x000056495bc53180 in ext_do_call (nk=<optimized out>, na=<optimized out>, flags=<optimized out>, pp_stack=0x7fe290ff8308, func=<function at remote 0x7fe2c7ff5158>)
    at ../Python/ceval.c:5049
#25 PyEval_EvalFrameEx () at ../Python/ceval.c:3290
#26 0x000056495bc5a286 in _PyEval_EvalCodeWithName () at ../Python/ceval.c:4033
#27 0x000056495bc564c9 in fast_function (nk=<optimized out>, na=<optimized out>, n=<optimized out>, pp_stack=0x7fe290ff8510, func=<optimized out>) at ../Python/ceval.c:4828
#28 call_function (oparg=<optimized out>, pp_stack=0x7fe290ff8510) at ../Python/ceval.c:4745
#29 PyEval_EvalFrameEx () at ../Python/ceval.c:3251
#30 0x000056495bc5593f in fast_function (nk=<optimized out>, na=<optimized out>, n=<optimized out>, pp_stack=0x7fe290ff8640, func=<optimized out>) at ../Python/ceval.c:4818
#31 call_function (oparg=<optimized out>, pp_stack=0x7fe290ff8640) at ../Python/ceval.c:4745
#32 PyEval_EvalFrameEx () at ../Python/ceval.c:3251
#33 0x000056495bc5593f in fast_function (nk=<optimized out>, na=<optimized out>, n=<optimized out>, pp_stack=0x7fe290ff8770, func=<optimized out>) at ../Python/ceval.c:4818
#34 call_function (oparg=<optimized out>, pp_stack=0x7fe290ff8770) at ../Python/ceval.c:4745
#35 PyEval_EvalFrameEx () at ../Python/ceval.c:3251
#36 0x000056495bc5b0df in _PyEval_EvalCodeWithName (qualname=0x0, name=<optimized out>, closure=0x0, kwdefs=0x0, defcount=0, defs=0x0, kwcount=0, kws=<optimized out>, 
    argcount=<optimized out>, args=<optimized out>, locals=<optimized out>, globals=<optimized out>, _co=<optimized out>) at ../Python/ceval.c:4033
#37 PyEval_EvalCodeEx () at ../Python/ceval.c:4054
#38 0x000056495bc977bf in function_call.lto_priv () at ../Objects/funcobject.c:627
#39 0x000056495bcde647 in PyObject_Call () at ../Objects/abstract.c:2166
#40 0x000056495bc53180 in ext_do_call (nk=<optimized out>, na=<optimized out>, flags=<optimized out>, pp_stack=0x7fe290ff8a28, func=<function at remote 0x7fe2c6c76620>)
    at ../Python/ceval.c:5049
#41 PyEval_EvalFrameEx () at ../Python/ceval.c:3290
#42 0x000056495bc5593f in fast_function (nk=<optimized out>, na=<optimized out>, n=<optimized out>, pp_stack=0x7fe290ff8b50, func=<optimized out>) at ../Python/ceval.c:4818
#43 call_function (oparg=<optimized out>, pp_stack=0x7fe290ff8b50) at ../Python/ceval.c:4745
#44 PyEval_EvalFrameEx () at ../Python/ceval.c:3251
#45 0x000056495bc5593f in fast_function (nk=<optimized out>, na=<optimized out>, n=<optimized out>, pp_stack=0x7fe290ff8c80, func=<optimized out>) at ../Python/ceval.c:4818
#46 call_function (oparg=<optimized out>, pp_stack=0x7fe290ff8c80) at ../Python/ceval.c:4745
#47 PyEval_EvalFrameEx () at ../Python/ceval.c:3251
#48 0x000056495bc5b0df in _PyEval_EvalCodeWithName (qualname=0x0, name=<optimized out>, closure=0x0, kwdefs=0x0, defcount=0, defs=0x0, kwcount=0, kws=<optimized out>, 
    argcount=<optimized out>, args=<optimized out>, locals=<optimized out>, globals=<optimized out>, _co=<optimized out>) at ../Python/ceval.c:4033
#49 PyEval_EvalCodeEx () at ../Python/ceval.c:4054
#50 0x000056495bc975d3 in function_call.lto_priv () at ../Objects/funcobject.c:627
#51 0x000056495bcde647 in PyObject_Call () at ../Objects/abstract.c:2166
#52 0x000056495bbfe94e in method_call.lto_priv () at ../Objects/classobject.c:330
#53 0x000056495bcde647 in PyObject_Call () at ../Objects/abstract.c:2166
#54 0x000056495bc91e30 in PyEval_CallObjectWithKeywords () at ../Python/ceval.c:4595
#55 0x000056495bd26962 in t_bootstrap () at ../Modules/_threadmodule.c:998
#56 0x00007fe2ca7a3494 in start_thread (arg=0x7fe290ff9700) at pthread_create.c:333
#57 0x00007fe2c9996aff in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97
```

**Comment by jlu5** [comment]
https://github.com/jlu5/PyLink/issues/585#issuecomment-415934639
