### ISSUE TITLE
pylink 3 crashes on inspircd 3

### ISSUE THREAD

**Issue by radmx** [jlu5/PyLink#663]
I have pylink 3 on inspircd 3 configure properly even with the target insp3 but crashes all time because of this:

[ERROR] (mynet) Caught error in handle_events, disconnecting!
Traceback (most recent call last):
File "/usr/local/lib/python3.5/dist-packages/pylinkirc-3.0.0-py3.5.egg/pylinkirc/classes.py", line 2026, in parse_irc_command
hook_args = self.handle_events(line)
File "/usr/local/lib/python3.5/dist-packages/pylinkirc-3.0.0-py3.5.egg/pylinkirc/protocols/ircs2s_common.py", line 356, in handle_events
parsed_args = func(sender, command, args)
File "/usr/local/lib/python3.5/dist-packages/pylinkirc-3.0.0-py3.5.egg/pylinkirc/protocols/ircs2s_common.py", line 690, in handle_quit
return {'text': args[0], 'userdata': userdata}
IndexError: list index out of range

and i see a shell output:
2021-02-11 14:48:04,419 [ERROR] (chat) The offending line was: <- :00BAAAAAY QUIT

why is this for ?? and how to avoid it, ???

**Comment by jlu5** [comment]
What kind of server is 00B? (Is it valid to send S2S QUIT without a message? I've never seen that before)

**Comment by radmx** [comment]
Its my Anope IRCD Services SID. ..is that maybe the issue source?

**Comment by genius3000** [comment]
Not common that I've seen but a QUIT (client or S2S) is valid without a message.
@radmx out of curiosity, what Anope related events take place just before this happens? I see a couple of spots in Anope where a QUIT is sent with no message.
