### ISSUE TITLE
ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:720)

### ISSUE THREAD

**Issue by radmx** [jlu5/PyLink#664]
Hi, now i have this issue: 
i've configure ircd ports 6900 to be serversonly and ssl, but when i try to ./pylink , output log comes like this and i can't get connected to any port

i've tested different serveronly ports and comes out the same

2021-02-13 05:31:48,292 [INFO] Connecting to network 'mynet' on 1.2.3.4:6900 
2021-02-13 05:31:48,293 [ERROR] (mynet) Disconnected from IRC:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pylinkirc-3.0.0-py3.5.egg/pylinkirc/classes.py", line 1896, in _connect
    self._socket.connect((ip, port))
  File "/usr/lib/python3.5/ssl.py", line 1027, in connect
    self._real_connect(addr, False)
  File "/usr/lib/python3.5/ssl.py", line 1018, in _real_connect
    self.do_handshake()
  File "/usr/lib/python3.5/ssl.py", line 996, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib/python3.5/ssl.py", line 641, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:720)

any idea?
Regards

**Comment by jlu5** [comment]
- Have you checked the troubleshooting guide at https://github.com/jlu5/PyLink/blob/master/docs/faq.md#pylink-wont-connect-to-my-network? I'm not sure if you redacted the IP in "1.2.3.4:6900", because I'm certain that's not the IP of a real IRCd.
- What OS are you using? Some older distro versions (Ubuntu 16.04, Debian 9) seems to have bugs in OpenSSL, which is what Python's SSL socket stack uses as a backend. These issues went away by upgrading the system: see #463

**Comment by jlu5** [comment]
Closing due to inactivity - anything using Python 3.5 is probably EOL as of 2021.
